/**
 * AUTO-GENERATED by scripts/calibrate-species-pk.ts — bounded correction factors
 * (0.6–1.6) that make the emergent terminal half-life ratio of the normalized
 * 3-compartment solver match the literature species ratio. Do not edit by hand;
 * rerun `npm run calibrate:pk`.
 */
export const SPECIES_PK_CALIBRATION: Record<string, number> = {
  "acepromazine:equine": 1.071,
  "dexmedetomidine:feline": 0.972,
  "dexmedetomidine:equine": 1.184,
  "dexmedetomidine:bovine": 1,
  "xylazine:feline": 0.962,
  "xylazine:equine": 0.899,
  "xylazine:bovine": 0.942,
  "midazolam:feline": 0.946,
  "midazolam:equine": 0.779,
  "midazolam:bovine": 0.946,
  "diazepam:feline": 0.864,
  "diazepam:equine": 0.72,
  "diazepam:bovine": 0.909,
  "morphine:feline": 0.893,
  "morphine:equine": 0.942,
  "morphine:bovine": 0.967,
  "methadone:feline": 0.814,
  "methadone:equine": 1.058,
  "methadone:bovine": 1,
  "fentanyl:feline": 0.85,
  "fentanyl:equine": 0.954,
  "butorphanol:feline": 0.759,
  "butorphanol:equine": 1.147,
  "butorphanol:bovine": 1.022,
  "buprenorphine:feline": 0.917,
  "buprenorphine:equine": 0.976,
  "tramadol:feline": 0.861,
  "tramadol:equine": 0.95,
  "propofol:feline": 0.6,
  "propofol:equine": 0.946,
  "propofol:bovine": 1,
  "alfaxalone:feline": 0.792,
  "alfaxalone:equine": 0.934,
  "ketamine:feline": 0.926,
  "ketamine:equine": 1.025,
  "ketamine:bovine": 1,
  "thiopental:feline": 0.99,
  "thiopental:equine": 1.029,
  "atipamezole:equine": 1.084,
  "naloxone:feline": 0.955,
  "lidocaine_2pct:feline": 0.849,
  "lidocaine_2pct:equine": 0.921,
  "lidocaine_2pct:bovine": 0.962
};

export const SPECIES_PK_CALIBRATION_META = {
  generatedAt: "2026-10-05T12:35:28.925Z",
  iterations: 5,
  converged: false,
  maxResidualPct: 19.76,
};
